config/routes.rb
Saaku20::Application.routes.draw do

  resources :press_releases do
    member do 
      get 'recent'
    end
  end

  namespace "admin" do
    resources :events, :users, :registrations, :broadcast_messages, :press_releases, :quick_links, :merchandises, :surveys, :alerts
  end
  
  #  resources :users do 
  #  member do 
  #    get 'change_password'
  #    post 'set_password'
  #  end
  #end

  resources :merchandises

  resources :quick_links
  resources :invites
  resources :registrations
  resources :localities
  resources :wards
  resources :events do
    resources :merchandises
    member do
      get 'attend'
      get 'attendees'
      get 'volunteer'
      get 'invite'
      get 'fetch_attendees'
      post 'register'
      post 'send_invite'
    end
  end
  resources :surveys 
  resources :surveyors 
  
  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "sign_up" => "users#new", :as => "sign_up"
  match "/confirm/:id" => "registrations#confirm"
  match "/confirm_participation/:guid" => "events#confirm_participation"
  match "/registrants/:id" => "events#fetch_attendees"
  match "/artwork" => "merchandises#index"
  match "/press" => "press_releases#recent"
  match "/change_password" => "users#change_password"
  match "/set_password" => "users#set_password"
  match "/fight" => "home#fight"
  match "/voteright" => "home#voteright"
  match "/about_us" => "home#about"
  match "/surveys/:survey_id/participate" => "surveyors#new"
  match "/surveys/:id/results" => "surveys#results"
  match "/disp_alerts" => "home#alerts"
  get "users/destroy"
  resources :users
  resources :sessions
  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  root :to => "home#index"

end

app/models/locality.rb
class Locality < ActiveRecord::Base
  attr_accessible :name, :lat, :lon

  def self.available(city)
    self.where("city = ?", city).length != 0
  end
end

app/controllers/localities_controller.rb
class LocalitiesController < ApplicationController
  def index
    @localities = Locality.all
  end

  def show
    @locality = Locality.find(params[:id])
  end

  def new
    @locality = Locality.new
  end

  def create
    @locality = Locality.new(params[:locality])
    if @locality.save
      redirect_to @locality, :notice => "Successfully created locality."
    else
      render :action => 'new'
    end
  end

  def edit
    @locality = Locality.find(params[:id])
  end

  def update
    @locality = Locality.find(params[:id])
    if @locality.update_attributes(params[:locality])
      redirect_to @locality, :notice  => "Successfully updated locality."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @locality = Locality.find(params[:id])
    @locality.destroy
    redirect_to localities_url, :notice => "Successfully destroyed locality."
  end
end

app/helpers/localities_helper.rb
module LocalitiesHelper
end

app/views/localities/_form.html.erb
<%= form_for @locality do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :ward_id %><br />
    <%= f.text_field :ward_id %>
  </p>
  <p>
    <%= f.label :lat %><br />
    <%= f.text_field :lat %>
  </p>
  <p>
    <%= f.label :lon %><br />
    <%= f.text_field :lon %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/localities/edit.html.erb
<% title "Edit Locality" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @locality %> |
  <%= link_to "View All", localities_path %>
</p>

app/views/localities/index.html.erb
<% title "Localities" %>

<table>
  <tr>
    <th>Name</th>
    <th>Ward</th>
    <th>Lat</th>
    <th>Lon</th>
  </tr>
  <% for locality in @localities %>
    <tr>
      <td><%= locality.name %></td>
      <td><%= locality.ward_id %></td>
      <td><%= locality.lat %></td>
      <td><%= locality.lon %></td>
      <td><%= link_to "Show", locality %></td>
      <td><%= link_to "Edit", edit_locality_path(locality) %></td>
      <td><%= link_to "Destroy", locality, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Locality", new_locality_path %></p>

app/views/localities/new.html.erb
<% title "New Locality" %>

<%= render 'form' %>

<p><%= link_to "Back to List", localities_path %></p>

app/views/localities/show.html.erb
<% title "Locality" %>

<p>
  <strong>Name:</strong>
  <%= @locality.name %>
</p>
<p>
  <strong>Ward:</strong>
  <%= @locality.ward_id %>
</p>
<p>
  <strong>Lat:</strong>
  <%= @locality.lat %>
</p>
<p>
  <strong>Lon:</strong>
  <%= @locality.lon %>
</p>

<p>
  <%= link_to "Edit", edit_locality_path(@locality) %> |
  <%= link_to "Destroy", @locality, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", localities_path %>
</p>