config/routes.rb
Saaku20::Application.routes.draw do

  resources :press_releases do
    member do 
      get 'recent'
    end
  end

  namespace "admin" do
    resources :events, :users, :registrations, :broadcast_messages, :press_releases, :quick_links, :merchandises, :surveys, :alerts
  end
  
  #  resources :users do 
  #  member do 
  #    get 'change_password'
  #    post 'set_password'
  #  end
  #end

  resources :merchandises

  resources :quick_links
  resources :invites
  resources :registrations
  resources :localities
  resources :wards
  resources :events do
    resources :merchandises
    member do
      get 'attend'
      get 'attendees'
      get 'volunteer'
      get 'invite'
      get 'fetch_attendees'
      post 'register'
      post 'send_invite'
    end
  end
  resources :surveys 
  resources :surveyors 
  
  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "sign_up" => "users#new", :as => "sign_up"
  match "/confirm/:id" => "registrations#confirm"
  match "/confirm_participation/:guid" => "events#confirm_participation"
  match "/registrants/:id" => "events#fetch_attendees"
  match "/artwork" => "merchandises#index"
  match "/press" => "press_releases#recent"
  match "/change_password" => "users#change_password"
  match "/set_password" => "users#set_password"
  match "/fight" => "home#fight"
  match "/voteright" => "home#voteright"
  match "/about_us" => "home#about"
  match "/surveys/:survey_id/participate" => "surveyors#new"
  match "/surveys/:id/results" => "surveys#results"
  match "/disp_alerts" => "home#alerts"
  get "users/destroy"
  resources :users
  resources :sessions
  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  root :to => "home#index"

end

app/models/event.rb
class Event < ActiveRecord::Base
  has_friendly_id :title, :use_slug => true

  attr_accessible :title, :description, :start_date, :end_date, :venue_location, :schedule, :contact, :city, :etype, :venue_directions_url, :venue, :rallyroute, :facebook_url, :twitter_url, :orkut_url, :cover_poster, :donate_box

  has_attached_file :venue, :styles => { :thumb => "100x100#", :small => "278x205>" }
  has_attached_file :rallyroute, :styles => { :thumb => "100x100#", :small => "278x205>" }
  has_attached_file :cover_poster, :styles => { :thumb => "100x100#", :small => "278x205>", :medium => "630x309>", :large => "900x>" }

  validates_attachment_size :venue, :less_than => 1.megabytes  
  validates_attachment_content_type :venue, :content_type => ['image/jpeg', 'image/png']  
  validates_attachment_size :rallyroute, :less_than => 1.megabytes  
  validates_attachment_content_type :rallyroute, :content_type => ['image/jpeg', 'image/png']  

  has_many :event_registrations
  has_many :registrations, :through => :event_registrations
  has_many :merchandises

  CITIES = ["Bangalore", "Mysore"]

  def self.upcoming
    Event.where("end_date >= ?", Time.now())
  end

  def self.recent
    Event.where("end_date <= ?", Time.now()).limit(3).order("start_date DESC")
  end

  def social_network?
    (!self.facebook_url.blank? || !self.twitter_url.blank? || !self.orkut_url.blank?)
  end

  def confirmed_supporters
    self.event_registrations.where("rtype = 1 and confirmed = true")
  end

  def unconfirmed_supporters
    self.event_registrations.where("rtype = 1 and confirmed = false")
  end
  
  def all_supporters
    self.event_registrations.where("rtype = 1")
  end

  def confirmed_volunteers
    self.event_registrations.where("rtype = 2 and confirmed = true")
  end

  def unconfirmed_volunteers
    self.event_registrations.where("rtype = 2 and confirmed = false")
  end
  
  def all_volunteers
    self.event_registrations.where("rtype = 2")
  end
  
  def all_registrants
    self.event_registrations
  end
  
end

app/controllers/admin/events_controller.rb
class Admin::EventsController < ApplicationController  
  load_and_authorize_resource 
  layout 'admin'

  def index
    @events = Event.all
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(params[:event])
    if @event.save
      redirect_to @event, :notice => "Successfully created event."
    else
      render :action => 'new'
    end
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])
    if @event.update_attributes(params[:event])
      redirect_to @event, :notice  => "Successfully updated event."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    redirect_to events_url, :notice => "Successfully destroyed event."
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  load_and_authorize_resource 
  
  def show
    @event = Event.find(params[:id])
  end
  
  def attend
    @event = Event.find(params[:id])
    @registration = Registration.new({:rtype => 1, :city => @event.city})
  end

  def attendees
    @event = Event.find(params[:id])
    @locs = @event.all_registrants.collect {|c| {:lat => c.registration.locality.lat, :lon => c.registration.locality.lon } }.to_json
  end

  def volunteer
    @event = Event.find(params[:id])
    @registration = Registration.new({:rtype => 2, :city => @event.city})
  end

  def invite
    @event = Event.find(params[:id])
    @invite = Invite.new()
  end

  def send_invite
    @event = Event.find(params[:id])
    @invite = Invite.new(params[:invite])
    if verify_recaptcha(:model => @invite, :message => "Invalid reCAPTCHA!") && @invite.save
      @invite.send_invite!(@event)
      redirect_to @event, :notice => "Your invite has been sent!"
    else
      render :action => 'invite'
    end
  end

  def register
    @event = Event.find(params[:id])
    @registration = Registration.new(params[:registration])
    @reg = Registration.find_by_email(@registration.email)
    unless verify_recaptcha(:model => @registration, :message => "Invalid reCAPTCHA!") && @registration.valid?
      if @registration.rtype == 1
        render :action => 'attend'
      elsif @registration.rtype == 2
        render :action => 'volunteer'
      end
      return;
    end
    unless @reg.nil?
      @er = EventRegistration.where("event_id = ? and registration_id = ?", @event.id, @reg.id).first
      if @er.nil?
        @er = EventRegistration.create!({:event => @event, :registration => @reg, :rtype => @registration.rtype, :guid => EventRegistration.gen_guid})
        RegistrationMailer.event_participation_confirmation(@er).deliver
        redirect_to @event, :notice => "Thank you for extending your support to the event! A confirmation email has been sent to your email address"
        return;
      else
        if @registration.rtype == @er.rtype
          @reg.update_attributes(params[:registration])
          redirect_to @event, :notice => "You have already registered for this event!"
          return;
        else
          @reg.update_attributes(params[:registration])
          @er.update_attributes({:rtype => @registration.rtype, :guid => EventRegistration.gen_guid})
          @er.registration.update_attributes({:volunteering_area => @registration.volunteering_area, :volunteer_description => @registration.volunteer_description})
          RegistrationMailer.event_participation_confirmation(@er).deliver
          redirect_to @event, :notice => "Thank you for extending your support to the event! A confirmation email has been sent to your email address"
          return;
        end
      end
    end
    if @registration.save
      EventRegistration.create!({:event => @event, :registration => @registration, :rtype => @registration.rtype, :guid => @registration.guid })
      RegistrationMailer.registration_confirmation(@registration).deliver
      redirect_to @event, :notice => "Thank you for extending your support to the event! A confirmation email has been sent for you to confirm your participation"
      return;
    else
      if @registration.rtype == 1
        render :action => 'attend'
      elsif @registration.rtype == 2
        render :action => 'volunteer'
      end
    end    
  end

  def confirm_participation
      @er = EventRegistration.find_by_guid(params[:guid])
      if @er.nil?
         render 'registrations/confirm'
         return;
      else
         @er.mark_confirmed
         message = "Thank you for confirming your participation in the event " if @er.rtype == 1
         message = "Thank you for your willingness to volunteer for the event " if @er.rtype == 2
         message << "<b>#{@er.event.title}</b>! Please spread a word about this event to your friends and colleagues by <A href='/events/#{@er.event.cached_slug}/invite'>Inviting</A> them to register!"
        redirect_to @er.event, :notice => message
      end
   end

  def fetch_attendees
    @event = Event.find(params[:id])
    @locs = @event.all_registrants.collect {|c| {:lat => c.registration.locality.lat, :lon => c.registration.locality.lon } }.to_json    
  end


end

app/helpers/admin/events_helper.rb
module Admin::EventsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/admin/events/_form.html.erb
<%= form_for ([:admin, @event], :html => {:multipart => true})  do |f| %>
  <%= render 'layouts/form_error', :target => @event %>
  <p>
    <%= f.label :title %>
    <%= f.text_field :title, :size => 80 %>
  </p>
  <p>
    <%= f.label :description %>
    <%= f.cktext_area :description %>
  </p>
  <p>
    <%= f.label :cover_poster %>
    <%= f.file_field :cover_poster %>
  </p>
  <p>
    <%= f.label :start_date %>
    <%= f.datetime_select :start_date, {:order => [:day, :month, :year]} %>
  </p>
  <p>
    <%= f.label :end_date %>
    <%= f.datetime_select :end_date, {:order => [:day, :month, :year]} %>
  </p>
  <p>
    <%= f.label :venue_location %>
    <%= f.text_field :venue_location, :size => 80 %>
  </p>
  <p>
    <%= f.label :schedule %>
    <%= f.text_area :schedule, :rows => 10, :cols => 110 %>
  </p>
  <p>
    <%= f.label :contact %>
    <%= f.text_field :contact, :size => 80 %> <br/>
    <span class="hint">( Use comma to separate multiple contact numbers Eg: Saravana - 9xxxxxxxxxx , Ravi - 95xxxxxxxx)</span>
  </p>
  <p>
    <%= f.label :city %>
    <%= f.select :city, Event::CITIES %>
  </p>
  <p>
    <%= f.label :facebook_url%>
    <%= f.text_field :facebook_url%>
  </p>
  <p>
    <%= f.label :twitter_url%>
    <%= f.text_field :twitter_url%>
  </p>
  <p>
    <%= f.label :orkut_url%>
    <%= f.text_field :orkut_url%>
  </p>
  <p>
    <%= f.label :etype %>
    <%= f.text_field :etype %>
  </p>
  <p>
    <%= f.label :Venue %>
    <%= f.file_field :venue %>
  </p>
  <p>
    <%= f.label :venue_directions_url %>
    <%= f.text_field :venue_directions_url %>
  </p>
  <p>
    <%= f.label :rallyroute %>
    <%= f.file_field :rallyroute %>
  </p>
  <p>
    <%= f.check_box :donate_box %>
    <%= f.label :donate_box, "Show Donation information in Event details page" %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/admin/events/edit.html.erb
<div class="form">
  <%= render 'form' %>
<p>
  <%= link_to "Show", @event %> |
  <%= link_to "View All", events_path %>
</p>
</div>

app/views/admin/events/index.html.erb
<table>
  <tr>
    <th>Title</th>
    <th>Start Date</th>
    <th>End Date</th>
    <th>Venue</th>
    <th>City</th>
  </tr>
  <% for event in @events %>
    <tr>
      <td><%= event.title %></td>
      <td><%= event.start_date %></td>
      <td><%= event.end_date %></td>
      <td><%= event.venue_location %></td>
      <td><%= event.city %></td>
      <td><%= link_to "Show", event %></td>
      <td><%= link_to "Edit", edit_admin_event_path(event) %></td>
      <td><%= link_to "Destroy", [:admin,event], :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Event", new_admin_event_path %></p>

app/views/admin/events/new.html.erb
<div class="form">
<%= render 'form' %>

<p><%= link_to "Back to List", events_path %></p>
</div>