config/routes.rb
Saaku20::Application.routes.draw do

  resources :press_releases do
    member do 
      get 'recent'
    end
  end

  namespace "admin" do
    resources :events, :users, :registrations, :broadcast_messages, :press_releases, :quick_links, :merchandises, :surveys, :alerts
  end
  
  #  resources :users do 
  #  member do 
  #    get 'change_password'
  #    post 'set_password'
  #  end
  #end

  resources :merchandises

  resources :quick_links
  resources :invites
  resources :registrations
  resources :localities
  resources :wards
  resources :events do
    resources :merchandises
    member do
      get 'attend'
      get 'attendees'
      get 'volunteer'
      get 'invite'
      get 'fetch_attendees'
      post 'register'
      post 'send_invite'
    end
  end
  resources :surveys 
  resources :surveyors 
  
  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "sign_up" => "users#new", :as => "sign_up"
  match "/confirm/:id" => "registrations#confirm"
  match "/confirm_participation/:guid" => "events#confirm_participation"
  match "/registrants/:id" => "events#fetch_attendees"
  match "/artwork" => "merchandises#index"
  match "/press" => "press_releases#recent"
  match "/change_password" => "users#change_password"
  match "/set_password" => "users#set_password"
  match "/fight" => "home#fight"
  match "/voteright" => "home#voteright"
  match "/about_us" => "home#about"
  match "/surveys/:survey_id/participate" => "surveyors#new"
  match "/surveys/:id/results" => "surveys#results"
  match "/disp_alerts" => "home#alerts"
  get "users/destroy"
  resources :users
  resources :sessions
  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  root :to => "home#index"

end

app/models/alert.rb
class Alert < ActiveRecord::Base
  
    
  validates_presence_of :content

end

app/controllers/admin/alerts_controller.rb
class Admin::AlertsController < ApplicationController
  load_and_authorize_resource
  layout 'admin'

  def index
    @alerts = Alert.all
  end
  
  def show
    @alert = Alert.find(params[:id])
  end
  
  def new
    @alert = Alert.new
  end
  
  def create
    @alert = Alert.new(params[:alert])
    if @alert.save
      flash[:notice] = "Successfully created Alert."
      redirect_to "/admin/alerts"
    else
      render :action => 'new'
    end
  end
  
  def edit
    @alert = Alert.find(params[:id])
  end
  
  def update
    @alert = Alert.find(params[:id])
    if @alert.update_attributes(params[:alert])
      flash[:notice] = "Successfully updated alert."
      redirect_to [:admin, @alert]
    else
      render :action => 'edit'
    end
  end
  
  def destroy
    @alert = Alert.find(params[:id])
    @alert.destroy
    flash[:notice] = "Successfully destroyed alert."
    redirect_to alerts_url
  end

end

app/views/admin/alerts/_form.html.erb
<div class='form'>
<%= render 'layouts/form_error', :target => @alert %>
<%= form_for [:admin, @alert] do |f| %>
  <p>
    <%= f.label "Content" %> <br/>
    <%= f.text_area :content%> 
  </p>
  <p>
    <%= f.label "Validity" %>
    <%= f.date_select :validity %> 
  </p>
  <br/>
  <p><%= f.submit %> Or <%= link_to "Cancel", "/admin/alerts" %></p>
<% end %>
</div>

app/views/admin/alerts/edit.html.erb
<%= render 'form' %>

<p>
  <%= link_to "Show", [:admin, @alert] %> |
  <%= link_to "View All", admin_alerts_path %>
</p>

app/views/admin/alerts/index.html.erb
<table>
  <tr>
    <th>Content</th>
    <th>Validity</th>
  </tr>
  <% for alert in @alerts %>
    <tr>
      <td><%= raw(alert.content) %></td>
      <td><%= alert.validity.strftime("%d-%m-%Y  %H:%M %P")%></td>
      <td><%= link_to "Edit", edit_admin_alert_path(alert) %></td>
      <td><%= link_to "Destroy", [:admin, alert], :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Alert", new_admin_alert_path %></p>

app/views/admin/alerts/new.html.erb
<%= render 'form' %>

<p><%= link_to "Back to List", admin_alerts_path %></p>

app/views/admin/alerts/show.html.erb
<p>
  <strong>Alert Content:</strong>
  <%= raw @alert.content %>
</p>
<p>
  <strong>Validity:</strong>
  <%= @alert.validity.strftime("%d %m %Y %H:%M %P")%>
</p>

<p>
  <%= link_to "Edit", edit_admin_alert_path(@alert) %> |
  <%= link_to "Destroy", [:admin, @alert], :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", admin_alerts_path %>
</p>