config/routes.rb
Saaku20::Application.routes.draw do

  resources :press_releases do
    member do 
      get 'recent'
    end
  end

  namespace "admin" do
    resources :events, :users, :registrations, :broadcast_messages, :press_releases, :quick_links, :merchandises, :surveys, :alerts
  end
  
  #  resources :users do 
  #  member do 
  #    get 'change_password'
  #    post 'set_password'
  #  end
  #end

  resources :merchandises

  resources :quick_links
  resources :invites
  resources :registrations
  resources :localities
  resources :wards
  resources :events do
    resources :merchandises
    member do
      get 'attend'
      get 'attendees'
      get 'volunteer'
      get 'invite'
      get 'fetch_attendees'
      post 'register'
      post 'send_invite'
    end
  end
  resources :surveys 
  resources :surveyors 
  
  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "sign_up" => "users#new", :as => "sign_up"
  match "/confirm/:id" => "registrations#confirm"
  match "/confirm_participation/:guid" => "events#confirm_participation"
  match "/registrants/:id" => "events#fetch_attendees"
  match "/artwork" => "merchandises#index"
  match "/press" => "press_releases#recent"
  match "/change_password" => "users#change_password"
  match "/set_password" => "users#set_password"
  match "/fight" => "home#fight"
  match "/voteright" => "home#voteright"
  match "/about_us" => "home#about"
  match "/surveys/:survey_id/participate" => "surveyors#new"
  match "/surveys/:id/results" => "surveys#results"
  match "/disp_alerts" => "home#alerts"
  get "users/destroy"
  resources :users
  resources :sessions
  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  root :to => "home#index"

end

app/models/ward.rb
class Ward < ActiveRecord::Base
  attr_accessible :name, :ward_no, :total_population, :area, :lat, :lon
  has_many :localities

  def self.available(city)
    self.where("city = ?", city).length != 0
  end
end

app/controllers/wards_controller.rb
class WardsController < ApplicationController
  def index
    @wards = Ward.all
  end

  def show
    @ward = Ward.find(params[:id])
  end

  def new
    @ward = Ward.new
  end

  def create
    @ward = Ward.new(params[:ward])
    if @ward.save
      redirect_to @ward, :notice => "Successfully created ward."
    else
      render :action => 'new'
    end
  end

  def edit
    @ward = Ward.find(params[:id])
  end

  def update
    @ward = Ward.find(params[:id])
    if @ward.update_attributes(params[:ward])
      redirect_to @ward, :notice  => "Successfully updated ward."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @ward = Ward.find(params[:id])
    @ward.destroy
    redirect_to wards_url, :notice => "Successfully destroyed ward."
  end
end

app/helpers/wards_helper.rb
module WardsHelper
end

app/views/wards/_form.html.erb
<%= form_for @ward do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :ward_no %><br />
    <%= f.text_field :ward_no %>
  </p>
  <p>
    <%= f.label :total_population %><br />
    <%= f.text_field :total_population %>
  </p>
  <p>
    <%= f.label :area %><br />
    <%= f.text_field :area %>
  </p>
  <p>
    <%= f.label :lat %><br />
    <%= f.text_field :lat %>
  </p>
  <p>
    <%= f.label :lon %><br />
    <%= f.text_field :lon %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/wards/edit.html.erb
<% title "Edit Ward" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @ward %> |
  <%= link_to "View All", wards_path %>
</p>

app/views/wards/index.html.erb
<% title "Wards" %>

<table>
  <tr>
    <th>Name</th>
    <th>Ward No</th>
    <th>Total Population</th>
    <th>Area</th>
    <th>Lat</th>
    <th>Lon</th>
  </tr>
  <% for ward in @wards %>
    <tr>
      <td><%= ward.name %></td>
      <td><%= ward.ward_no %></td>
      <td><%= ward.total_population %></td>
      <td><%= ward.area %></td>
      <td><%= ward.lat %></td>
      <td><%= ward.lon %></td>
      <td><%= link_to "Show", ward %></td>
      <td><%= link_to "Edit", edit_ward_path(ward) %></td>
      <td><%= link_to "Destroy", ward, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Ward", new_ward_path %></p>

app/views/wards/new.html.erb
<% title "New Ward" %>

<%= render 'form' %>

<p><%= link_to "Back to List", wards_path %></p>

app/views/wards/show.html.erb
<% title "Ward" %>

<p>
  <strong>Name:</strong>
  <%= @ward.name %>
</p>
<p>
  <strong>Ward No:</strong>
  <%= @ward.ward_no %>
</p>
<p>
  <strong>Total Population:</strong>
  <%= @ward.total_population %>
</p>
<p>
  <strong>Area:</strong>
  <%= @ward.area %>
</p>
<p>
  <strong>Lat:</strong>
  <%= @ward.lat %>
</p>
<p>
  <strong>Lon:</strong>
  <%= @ward.lon %>
</p>

<p>
  <%= link_to "Edit", edit_ward_path(@ward) %> |
  <%= link_to "Destroy", @ward, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", wards_path %>
</p>